global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "django"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]
